- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: variables/output_vars1.yml
    - name: Import VPC variables
      include_vars: variables/ami_ids

    - name: Creating ec2 key for nginx
      ec2_key:
       name: nginxkey
       region: "{{region}}"
      register: nginxkey

    - name: Saving the key into file
      copy: 
        content: "{{nginxkey.key.private_key}}"
        dest: "./nginxkey.pem"
        mode: 0600
      when: nginxkey.changed

    - name: Creating the security group for NGINX server
      ec2_group:
        name: NGINX-Server
        description: Allow port 80 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}" 
        rules: 
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
      register: nginx_out


    - name: Creating the security group for stack
      ec2_group:
        name: stacksg
        description: Allow port 80 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no 
        rules: 
         - proto: tcp
           from_port: 80
           to_port: 80
           group_id: "{{nginx_out.group_id}}"
         - proto: tcp
           from_port: 22
           to_port: 22
           group_id: "{{BastionSGid}}"             
      register: stacksg_out

    - name: Updating security group for stack
      ec2_group:
        name: stacksg
        description: Allow port 22 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no 
        rules: 
         - proto: all
           group_id: "{{stacksg_out.group_id}}"
      register: stacksgupdated_out

    - name: Create EC2 Instance for NGINX
      ec2:
        key_name: nginxkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ ubuntu_image }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "WEB01 NGINX"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "web01"
          Project: Personal
          Owner: Mehmood
        group_id: "{{stacksg_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: fornginxout

    - debug: 
        var: fornginxout

    - name: Create EC2 Instance for TOMCAT
      ec2:
        key_name: nginxkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ ubuntu_image }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "TOMCAT"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "tomcat"
          Project: Personal
          Owner: Mehmood
        group_id: "{{stacksg_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: fortomcatout

    - debug: 
        var: fortomcatout

    - name: Create EC2 Instance for memcache
      ec2:
        key_name: nginxkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ ubuntu_image }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "MEMCACHE"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "memcache"
          Project: Personal
          Owner: Mehmood
        group_id: "{{stacksg_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: formemcacheout

    - debug: 
        var: formemcacheout

    - name: Create EC2 Instance for rabbitmq
      ec2:
        key_name: nginxkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ ubuntu_image }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "RABBITMQ"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "rabbitmq"
          Project: Personal
          Owner: Mehmood
        group_id: "{{stacksg_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: forrabbitmqout

    - debug: 
        var: forrabbitmqout

    - name: Create EC2 Instance for Database
      ec2:
        key_name: nginxkey
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ ubuntu_image }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Database"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "database"
          Project: Personal
          Owner: Mehmood
        group_id: "{{stacksg_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: fordatabaseout

    - debug: 
        var: fordatabaseout


