- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: variables/output_vars1.yml
    - name: Import VPC variables
      include_vars: variables/ami_ids

    - name: Creating ec2 key for nginx
      ec2_key:
       name: nginxkey
       region: "{{region}}"
      register: nginxkey

    - name: Saving the key into file
      copy: 
        content: "{{nginxkey.key.private_key}}"
        dest: "./nginxkey.pem"
        mode: 0600
      when: nginxkey.changed

    - name: Creating the security group for NGINX server
      ec2_group:
        name: NGINX-Server
        description: Allow port 80 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}" 
        rules: 
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
      register: nginx_out


    - name: Creating the security group for stack
      ec2_group:
        name: stacksg
        description: Allow port 80 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no 
        rules: 
         - proto: tcp
           from_port: 80
           to_port: 80
           group_id: "{{nginx_out.group_id}}"
         - proto: tcp
           from_port: 22
           to_port: 22
           group_id: "{{BastionSGid}}"             
      register: stacksg_out

    - name: Updating security group for stack
      ec2_group:
        name: stacksg
        description: Allow port 22 from everywhere and all ports within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no 
        rules: 
         - proto: all
           group_id: "{{stacksg_out.group_id}}"
      register: stacksgupdated_out