- name: Setup the bastion host for access
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Importing the variables
      include_vars: variables/output_vars1.yml
    - name: Importing the variables
      include_vars: variables/creatingVPC.yml
    - name: Creating ec2 key
      ec2_key:
       name: mehmood-key1
       region: "{{region}}"
      register: keyoutput22

    - name: Saving the key into file
      copy: 
        content: "{{keyoutput22.key.private_key}}"
        dest: "./bastion-key22.pem"
        mode: 0600
      when: keyoutput22.changed

    - name: Creating the security group
      ec2_group:
        name: Bastion-Host
        description: Allow port 22 and all ports within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}" 
        rules: 
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: "{{My_IP}}"  
      register: bastionSG

    - name: Create EC2 Instance for bastion
      ec2:
        key_name: mehmood-key1
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_Host"
          Project: Personal
          Owner: Mehmood
        exact_count: 1
        count_tag:
          Name: "Bastion_Host"
          Project: Personal
          Owner: Mehmood
        group_id: "{{bastionSG.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: ec2instanceout

    - debug: 
        var: ec2instanceout

    - name: insert the bastion host output in the variable file
      blockinfile:
       path: variables/output_vars1.yml
       backup: yes
       block: |
         BastionSGid: {{bastionSG.group_id}}