- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: variables/creatingVPC.yml

    - name: Create the VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcoutput

    - debug:
        var: vpcoutput
      
    - name: Creating Public Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub1
      register: pubsub1output
    
    - debug: 
        var: pubsub1output

    - name: Creating Public Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub2
      register: pubsub2output
    
    - debug: 
        var: pubsub2output

    - name: Creating Public Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub3
      register: pubsub3output
    
    - debug:
        var: pubsub3output

    - name: Creating Pvt Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub1
      register: privsub1output
    
    - debug: 
        var: privsub1output

    - name: Creating Private Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub2
      register: privsub2output
    
    - debug: 
        var: privsub2output

    - name: Creating Private Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub3
      register: privsub3output
    
    - debug:
        var: privsub3output

    - name: Creating internet GWs
      ec2_vpc_igw:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
         Name: internet-gateway
      register: igwvpc

    - debug:
        var: igwvpc

    - name: Creating the route tables
      ec2_vpc_route_table:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        tags:
         Name: routetablepublic
        subnets: 
          - "{{pubsub1output.subnet.id}}"
          - "{{pubsub2output.subnet.id}}"
          - "{{pubsub3output.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igwvpc.gateway_id}}"
      register: routetablepublic

    - name: Creating the NAT GATEWAY
      ec2_vpc_nat_gateway:
        region: "{{region}}"
        state: "{{state}}"
        subnet_id: "{{pubsub1output.subnet.id}}"
        wait: yes
        if_exist_do_not_create: true
      register: natgatewaypub1
    - debug:
        var: natgatewaypub1
  
  
    - name: Setup private subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcoutput.vpc.id}}"
        region: "{{region}}"
        tags:
         Name: routetableprivate
        subnets: 
          - "{{privsub1output.subnet.id}}"
          - "{{privsub2output.subnet.id}}"
          - "{{privsub3output.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{natgatewaypub1.nat_gateway_id}}"
      register: routetableprivate

    - debug:
        var: "{{item}}"
      loop:
        - vpcoutput.vpc.id
        - pubsub1output.subnet.id
        - pubsub2output.subnet.id
        - pubsub3output.subnet.id
        - privsub1output.subnet.id
        - privsub2output.subnet.id
        - privsub3output.subnet.id
        - natgatewaypub1.nat_gateway_id   
        - routetablepublic.route_table.id    
        - routetableprivate.route_table.id 
        - igwvpc.gateway_id

    - set_facts: 
        vpcid: "{{vpcoutput.vpc.id}}"
        pubsub1id: "{{pubsub1output.subnet.id}}"
        pubsub2id: "{{pubsub2output.subnet.id}}"
        pubsub3id: "{{pubsub3output.subnet.id}}"
        privsub1id: "{{privsub1output.subnet.id}}"
        privsub2id: "{{privsub2output.subnet.id}}"
        privsub3id: "{{privsub3output.subnet.id}}"
        natgatewaypub1id: "{{natgatewaypub1.nat_gateway_id}}"   
        routetablepublicid: "{{routetablepublic.route_table.id}}" 
        routetableprivateid: "{{routetableprivate.route_table.id}}"
        igwvpcid: "{{igwvpc.gateway_id}}"
        cacheable: yes
    - name: Copy variables to file 
      copy:
        content: "vpcid:   {{vpcoutput.vpc.id}}\n pubsub1id:{{pubsub1output.subnet.id}}\n pubsub2id:{{pubsub2output.subnet.id}}\n pubsub3id:{{pubsub3output.subnet.id}}\n privsub1id:{{privsub1output.subnet.id}}\n privsub2id:{{privsub2output.subnet.id}}\n privsub3id:{{privsub3output.subnet.id}}\n natgatewaypub1id:{{natgatewaypub1.nat_gateway_id}}\n routetablepublicid:{{routetablepublic.route_table.id}} \n routetableprivateid:{{routetableprivate.route_table.id}}\n igwvpcid:{{igwvpc.gateway_id}}"   
        dest: vars/output_vars
