- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: variables/creatingVPC.yml

    - name: Create the VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcoutput

    - debug:
        var: vpcoutput
      
    - name: Creating Public Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub1
      register: pubsub1output
    
    - debug: 
        var: pubsub1output

    - name: Creating Public Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub2
      register: pubsub2output
    
    - debug: 
        var: pubsub2output

    - name: Creating Public Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: yes
        tags: 
         Name: mehmood-pubsub3
      register: pubsub3output
    
    - debug:
        var: pubsub3output

    - name: Creating Pvt Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub1
      register: privsub1output
    
    - debug: 
        var: privsub1output

    - name: Creating Private Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub2
      register: privsub2output
    
    - debug: 
        var: privsub2output

    - name: Creating Private Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcoutput.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: no
        tags: 
         Name: mehmood-privsub3
      register: privsub3output
    
    - debug:
        var: privsub3output